---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-image-cleanup
  labels:
    tier: management
    app: docker-image-cleanup
spec:
  selector:
    matchLabels:
      name: docker-image-cleanup
  template:
    metadata:
      labels:
        name: docker-image-cleanup
    spec:
      containers:
        - resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
          securityContext:
            privileged: true
          image: aksrepos.azurecr.io/fundamental/base-docker:v0.0.5
          imagePullPolicy: IfNotPresent
          name: docker-image-cleanup
          command: ["/bin/bash", "-c"]
          args:
            - >
              while true; do
                docker system prune --all --filter until=$(date -d "15 days ago" +%s) -f;
                sleep 86400;
              done
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock